# Generated by Django 5.0.2 on 2024-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educativeoffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='codigoPostal',
            field=models.IntegerField(default=0),
        ),
    ]
